# https://wiki.hypr.land/Configuring/Variables/

$primary_accent = rgba(ddddddff)

$white = rgba(ffffffff)
$gray_1 =
$gray_2 =
$gray_3 =
$black =

$red = rgba(de2566aa)
$orange =
$yellow =
$green = rgba(00ff99aa)
$blue = rgba(33ccffaa)
$purple =
$violet =

$shadow_black = rgba(10,10,10,0.3)

$border_grey = rgba(505050bb)
